:playblue: Jvnko Loves You - Sewerslvt
Beto :)
beto82510p
Compartiendo su pantalla
en:#general 
Rythm
APP
 — ayer a las 22:08
Now playing: I Want You To Know - Zedd, Selena Gomez ✨
Now playing: Counting Stars - OneRepublic ✨
Ean — ayer a las 22:15
Tipo de archivo adjunto: unknown
MinecraftRegular-Bmg3.ttf
13.66 KB
//fuente
 Font miFuente = LoadFont("MinecraftRegular-Bmg3.ttf");
Rythm
APP
 — ayer a las 22:16
Now playing: Hymn for the Weekend - Coldplay ✨
Now playing: Viva La Vida - Coldplay ✨
Rythm
APP
 — ayer a las 22:24
Now playing: ...Baby One More Time - Britney Spears ✨
Now playing: Heart Attack - One Direction ✨
Now playing: Riptide - Vance Joy ✨
Rythm
APP
 — ayer a las 22:34
Now playing: Does He Know? - One Direction ✨
Ean — ayer a las 22:36
Texture2D portada = LoadTexture("src/imagen/portada.png");
// En lugar de DrawTextEx(...)
DrawTexture(portada, screenWidth/2 - portada.width/2, 150, WHITE);
Imagen
Rythm
APP
 — ayer a las 22:36
Now playing: She's Not Afraid - One Direction ✨
Now playing: Ophelia - The Lumineers ✨
Ean — ayer a las 22:40
Imagen
Rythm
APP
 — ayer a las 22:42
Now playing: I Would - One Direction ✨
Ean — ayer a las 22:43
Imagen
Rythm
APP
 — ayer a las 22:45
Now playing: Dusk Till Dawn (feat. Sia) - Radio Edit - ZAYN, Sia ✨
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Duele El Amor - Aleks Syntek, Ana Torroja (4:35)
Position 1
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued De Noche En La Ciudad - Aleks Syntek (3:20)
Position 2
:premium_logo_icon:
 Supporting artists matters
:premium_support_artists_solid:
 Your Premium subscription pays artists and keeps Rythm running.
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Mis Impulsos Sobre Ti - Aleks Syntek y la Gente Normal (4:33)
Position 3
@Ean used /remove on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Removed Mis Impulsos Sobre Ti - Aleks Syntek y la Gente Normal
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Tú Necesitas - Aleks Syntek (5:00)
Position 3
Now playing: Duele El Amor - Aleks Syntek, Ana Torroja
Rythm
APP
 — ayer a las 22:53
Now playing: De Noche En La Ciudad - Aleks Syntek
Now playing: Tú Necesitas - Aleks Syntek
Rythm
APP
 — ayer a las 23:01
Now playing: Bombón De Azúcar - Ricky Martin ✨
Now playing: No Puedo Estar Sin Ti - Mœnia ✨
Rythm
APP
 — ayer a las 23:10
Now playing: Baila - Ragazzi ✨
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued ROSONES - Tito Double P (2:57)
Position 1
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued DEMBOW BÉLICO - Tito Double P, Joel De La P, Luis R Conriquez (2:06)
Position 2
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued LINDA - Tito Double P, Neton Vega (3:44)
Position 3
Now playing: ROSONES - Tito Double P
Now playing: DEMBOW BÉLICO - Tito Double P, Joel De La P, Luis R Conriquez
Rythm
APP
 — ayer a las 23:18
Now playing: LINDA - Tito Double P, Neton Vega
:premium_logo_icon:
 Want uninterrupted listening?
:premium_no_interruptions_solid:
 Premium gives you ad-free unlimited listening without interruptions.
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Summit (feat. Ellie Goulding) - Skrillex, Ellie Goulding (6:13)
Position 1
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Ruffneck - Flex - Skrillex (4:43)
Position 2
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Make It Bun Dem - Skrillex, Damian "Jr Gong" Marley (3:33)
Position 3
Now playing: Summit (feat. Ellie Goulding) - Skrillex, Ellie Goulding
Rythm
APP
 — ayer a las 23:28
Now playing: Ruffneck - Flex - Skrillex
Now playing: Make It Bun Dem - Skrillex, Damian "Jr Gong" Marley
Rythm
APP
 — ayer a las 23:35
Now playing: Ragga Bomb (with Ragga Twins) - Skrillex, Ragga Twins ✨
Now playing: All Is Fair in Love and Brostep (with Ragga Twins) - Skrillex, Ragga Twins ✨
Rythm
APP
 — ayer a las 23:44
Now playing: Nuclear (Hands Up) - Zomboy ✨
Now playing: Internet Friends - Knife Party ✨
Rythm
APP
 — ayer a las 23:54
Now playing: Bad Intentions - Zomboy ✨
Ean — ayer a las 23:58
https://www.canva.com/design/DAG658WMu_g/ngZGkdGwtwLED77UdQuSiw/edit?utm_content=DAG658WMu_g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Canva
Presentacion Lenguaje C
Presentacion Lenguaje C
Rythm
APP
 — ayer a las 23:58
Now playing: Cinema (feat. Gary Go) - Skrillex Remix - Benny Benassi, Gary Go, Skrillex ✨
Rythm
APP
 — 0:03
Now playing: Terror Squad - Zomboy ✨
Now playing: I Can't Stop - Flux Pavilion ✨
Rythm
APP
 — 0:12
Now playing: Sunlight - Modestep ✨
Now playing: Vancouver Beatdown - Zomboy ✨
Ean — 0:19
Imagen
Rythm
APP
 — 0:21
Now playing: Black Magic (Kill The Noise Pt. 2) - Kill The Noise ✨
Now playing: Gem Shards - MUST DIE! ✨
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Countdown - 2020 Remaster - John Coltrane (2:25)
Position 1
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Giant Steps - 2020 Remaster - John Coltrane (4:47)
Position 2
Rythm
APP
 — 0:30
Now playing: Countdown - 2020 Remaster - John Coltrane
Now playing: Giant Steps - 2020 Remaster - John Coltrane
@Ean used /play on the web app
⎯⎯⎯⎯⎯⎯⎯⎯
:rythmblue:
 Queued Mr. Kill Myself - Sewerslvt (7:51)
Position 1
Now playing: Mr. Kill Myself - Sewerslvt
Rythm
APP
 — 0:45
Now playing: Kawaii Razor Blades - Sewerslvt ✨
Now playing: Fine Night - Goreshit ✨
Rythm
APP
 — 0:56
Now playing: My Head Hurts - strxwberrymilk ✨
Now playing: all the joy in life was gone once you left - Sewerslvt ✨
Rythm
APP
 — 1:05
Now playing: AM FM - Vertigoaway ✨
Now playing: Felt Good - Golemm ✨
Now playing: Ecifircas - Sewerslvt ✨
Rythm
APP
 — 1:14
Now playing: sick, twisted, demented - Sewerslvt ✨
Now playing: I Break My Heart & Yours - Sewerslvt ✨
Rythm
APP
 — 1:22
Now playing: Cyberia Lyr1 - Sewerslvt ✨
Now playing: Fleeting Frozen Heart - Xxtarlit⚸ ✨
Rythm
APP
 — 1:30
Now playing: Ethereal - Jaegershu ✨
Ean — 1:31
Rythm
APP
 — 1:32
Now playing: my room is upside down - Deathbrain ✨
Now playing: Untouchable - Golemm ✨
Now playing: DESTROY The Wired - TOKYOPILL ✨
¡Sííí, has llegado, 
TTS Bot
! — 1:37
TTS Bot
APP
 — 1:37
Select a channel!
Haz una selección
TTS Bot
APP
 — 1:37
TTS Bot: Freshly rewritten in Rust!
Currently in:
:small_blue_diamond:
 8631 voice channels
:small_blue_diamond:
 993,249 servers
Currently using:
:small_orange_diamond:
 880 shards
:small_orange_diamond:
 46,130MB of RAM
and can be used by 87,092,428 people!
Imagen
Time to fetch: 218.65ms
Support Server: https://discord.gg/zWPWwQC
Repository: https://github.com/Discord-TTS/Bot
TTS Bot
APP
 — 1:37

gothquesadilla
TTS Bot has been setup!
TTS Bot will now accept commands and read from ⁠planes-de-quedadas.
Just do /join and start talking!
Imagen
There are loads of customizable settings, check out `/help set`
Rythm
APP
 — 1:38
Now playing: カガミ - AKIBA ✨
Now playing: Beat the shit out of the person - EVABOY ✨
Now playing: Yandere Complex - Sewerslvt ✨
Rythm
APP
 — 1:48
Now playing: S u r r e a l i t y - TOKYOPILL ✨
Now playing: CODE - Nedaj ✨
Ean — 1:53
Imagen
Rythm
APP
 — 1:53
Now playing: GORE-TEX COVERS MY SOUL - Blksmiith ✨
Now playing: Cyberia Lyr2 - Sewerslvt ✨
Beto :) — 1:58
https://prod.liveshare.vsengsaas.visualstudio.com/join?F205E233B1A24B1D657CBDC56DA352EA4B31
Visual Studio Code for the Web
Build with Visual Studio Code, anywhere, anytime, entirely in your browser.
Rythm
APP
 — 2:00
Now playing: Emptiness - TOKYOPILL ✨
Now playing: Which one of the Triplets? - Yesterdayneverhappened ✨
Now playing: Fortified Residential Zone - 3mouth ✨
Now playing: Nintendo DS Soul Injection - bye2 ✨
Rythm
APP
 — 2:12
Now playing: Blazing in the Dark - GnB Chili ✨
Now playing: I Bleed - Sewerslvt ✨
griqk — 2:14
#include <raylib.h>
#include <stdlib.h>
#include <time.h>
#include "ball.h"
#include "orificios.h"
#include "estados.h"
Expandir
message.txt
25 KB
Rythm
APP
 — 2:17
Now playing: Jvnko Loves You - Sewerslvt ✨
﻿
#include <raylib.h>
#include <stdlib.h>
#include <time.h>
#include "ball.h"
#include "orificios.h"
#include "estados.h"
#include <string.h> // Necesario
#include <stdio.h>  // Necesario

constexpr int filas = 5;    // filas del tablero
constexpr int columnas = 5; // columnas del tablero

void DrawHole(Texture2D texture, Rectangle hitbox, float scale);

// hola

int main()
{
    InitAudioDevice();
    /*************************TAMAÑO DE LA PANTALLA (NO MOVER)************************************ */
    constexpr int screenWidth = 1500;
    constexpr int screenHeight = 853;

    /************************************************************************* */

    /************************BORDES DE LOS RECTANGULOS************************** */
    float redondeo = 0.2; // entre 0.0 y 1.0
    int segnmentos = 10;  // qué tan suave es la curva
    /************************************************************************* */

    Ball ball;

    InitWindow(screenWidth, screenHeight, "MACACO MARBLE ULTIMATE"); // titulo

    Image icon = LoadImage("imagen/orificios/icono.png"); // carga icono

    SetWindowIcon(icon); // muestra icono

    Texture2D tablero = LoadTexture("imagen/fondo.jpeg"); // fondo de jungla

    Image fondotablero = LoadImage("imagen/fondotab.png"); // fondo de madera

    Font miFuente = LoadFont("fuentestxt/LuckiestGuy-Regular.ttf"); // fuente de texto
    Font fuentemine = LoadFont("fuentestxt/MinecraftRegular-Bmg3.ttf");

    Texture2D texturatab = LoadTextureFromImage(fondotablero); // carga textura de madera
    Texture2D portada = LoadTexture("imagen/portada.png");
    // En lugar de DrawTextEx(...)

    /******************************* TIPO DE PUNTAJE  **************************************** */
    Texture2D orvacio1 = LoadTexture("imagen/orificios/orificio1.png");
    Texture2D orvacio2 = LoadTexture("imagen/orificios/orificio2.png");
    Texture2D orvacio3 = LoadTexture("imagen/orificios/orificio3.png");
    Texture2D orvacio4 = LoadTexture("imagen/orificios/orificio4.png");
    Texture2D bomba = LoadTexture("imagen/orificios/bomb.png");

    Texture2D bombaexplo = LoadTexture("imagen/orificios/explosion.png");
    Texture2D orlleno1 = LoadTexture("imagen/orificios/orilleno1.png");
    Texture2D orlleno2 = LoadTexture("imagen/orificios/orilleno2.png");
    Texture2D orlleno3 = LoadTexture("imagen/orificios/orilleno3.png");
    Texture2D orlleno4 = LoadTexture("imagen/orificios/orilleno4.png");
    /******************************************************************** */
    Music musica = LoadMusicStream("musica/Cumbia.ogg");
    Music intro = LoadMusicStream("musica/inicio.ogg");

    PlayMusicStream(intro);
    SetMusicVolume(intro, 1);

    PlayMusicStream(musica);
    SetMusicVolume(musica, 1);

    SetTargetFPS(60); // FPS

    Rectangle puntaje = {30, 100, 370, 700}; // el que muestra el puntaje

    Rectangle caja = {500, 100, 900, 700}; // tamaño del tablero

    Cell cells[filas][columnas]; // matriz de celdas

    /******************DECLARACIONES****************** */
    int casillascol;   // casillas de la col
    int casillasfil;   // casillas por fila
    /* float chico; */ // a la que se le asigna el menor valor
    /* float radioori; */
    int puntajefinal = 0;
    int puntajeobjetivo;
    int promedio;
    int oportunidades;
    int nivel = 1; // 
    int opcs[20];
    int nopcs;
    int suma = 0;
    /****************************************************************************** */

    /*********************************HITBOX****************************************** */
    casillascol = (int)(caja.width / columnas); // ancho entero por columna
    casillasfil = (int)(caja.height / filas);   // alto entero por filafff

    /****************************************POSICION DE LA TEXTURA DE MADERA********************************************************** */
    Rectangle sourceRec = {0, 0, float(texturatab.width), float(texturatab.height)}; // donde se va aponer
    Rectangle destRec = caja;                                                        // donde se dibuja
    Vector2 origin = {0, 0};

    // --- VARIABLES IMPLEMENTADAS ---
    Rectangle btnJugar = {screenWidth / 2.0f - 150, screenHeight / 2.0f + 50, 300, 80}; 
    
    char inputTexto[10] = ""; 
    int contadorTeclas = 0;
    bool calculoRealizado = false;
    int bolasCapturadas[4] = {0, 0, 0, 0}; 
    Rectangle btnComprobar = { screenWidth/2.0f - 125, 650, 250, 60 };
    int intentos = 3; 
    // -------------------------------

    /***************************PARTE LOGICA DEL JUEGO************************************** */

    oportunidades = 5;

    nopcs = 0;

    switch (nivel)
    {
    case 1:
        // Nivel 1: SOLO valores positivos
        opcs[0] = 1;
        opcs[1] = 10;
        opcs[2] = 100;
        opcs[3] = 1000;
        opcs[4] = 100;
        nopcs = 5; // cantidad REAL de valores
        break;

    case 2:
        // Nivel 2: Positivos + negativos
        opcs[0] = -1;
        opcs[1] = -10;
        opcs[2] = -100;
        opcs[3] = -1000;
        opcs[4] = 1;
        opcs[5] = 10;
        opcs[6] = 100;
        opcs[7] = 1000;
        opcs[8] = 1;
        opcs[9] = 10;
        opcs[10] = 100;
        opcs[11] = 1;
        opcs[12] = 10;
        opcs[13] = 100;
        opcs[14] = 1000;

        nopcs = 15;
        break;

    case 3:
        opcs[0] = -1;
        opcs[1] = -10;
        opcs[2] = -100;
        opcs[3] = -1000;
        opcs[4] = 1;
        opcs[5] = 10;
        opcs[6] = 100;
        opcs[8] = 1;
        opcs[9] = 10;
        opcs[10] = 100;
        opcs[11] = 1;
        opcs[12] = 10;
        opcs[13] = 100;
        opcs[14] = 1000;
        

        nopcs = 15;
        break;

    default:
        opcs[0] = 1;
        nopcs = 1;
        break;
    }

    /********************************************************************************** */

    for (int i = 0; i < nopcs; i++)
    {
        suma += opcs[i];
    }

    promedio = suma / nopcs;

    for (int i = 0; i < filas; i++)
    {
        for (int j = 0; j < columnas; j++)
        {
            cells[i][j].valor = opcs[rand() % nopcs]; // asigna un valor aleatorio a la celda
            cells[i][j].ocupado = 0;
            cells[i][j].hitbox.x = caja.x + j * casillascol;
            cells[i][j].hitbox.y = caja.y + i * casillasfil;
            cells[i][j].hitbox.width = casillascol;
            cells[i][j].hitbox.height = casillasfil;
        }
    }

    int rangomin = promedio * 6.3;

    puntajeobjetivo = 1 + rand() % rangomin + (rangomin * 1.1);

    /*************************************************************** */

    /*************************************************************************************** */
    while (!WindowShouldClose())
    {
        UpdateMusicStream(intro);
        UpdateMusicStream(musica);

        // ================== BLOQUE DE MENÚ ==================
        if (estado_j == MENU)
        {
            Vector2 mousePos = GetMousePosition();
            if (CheckCollisionPointRec(mousePos, btnJugar)) {
                if (IsMouseButtonPressed(MOUSE_BUTTON_LEFT)) {
                    estado_j = INCIAJUEGO; 
                }
            }

            BeginDrawing();
            ClearBackground(BLACK);            
            DrawTexture(tablero, 0, 0, WHITE); 
            DrawTexture(portada, (screenWidth / 2) - (portada.width / 2), 100, WHITE);

            Color colorBtn = CheckCollisionPointRec(mousePos, btnJugar) ? ORANGE : GRAY;
            DrawRectangleRec(btnJugar, colorBtn);
            DrawRectangleLinesEx(btnJugar, 4, BLACK);
            DrawTextEx(fuentemine, "JUGAR", {btnJugar.x + 70, btnJugar.y + 10}, 60, 2, WHITE);
            EndDrawing();
            continue; 
        }
c


        float dt = GetFrameTime();
        BeginDrawing();
        ClearBackground(BLACK); 
        /*************************F O N D O***************************** */
        DrawTexture(tablero, 0, 0, WHITE); // DIBUJA EL fondo
        /*************************************************** */

        /****************************P U N T A J E*******************************************/
        DrawRectangleRounded(puntaje, redondeo, segnmentos, BLACK);           
        DrawRectangleRoundedLinesEx(puntaje, redondeo, segnmentos, 10, WHITE);
        
        DrawTextEx(miFuente, "PUNTAJE:", {puntaje.x * 5, puntaje.y + 10}, 30, 2, YELLOW);
        DrawText(TextFormat("NIVEL: %d", nivel), puntaje.x + 30, puntaje.y + 400, 30, ORANGE);

        /******************************************************************************* */

        /**********************************T A B L E R O************************************* */
        DrawTexturePro(texturatab, sourceRec, destRec, origin, 0.0f, WHITE);
        DrawRectangleRoundedLinesEx(caja, redondeo, segnmentos, 10.0f, BLACK); 
        DrawTexturePro(texturatab, sourceRec, destRec, origin, 0.0f, WHITE);

        for (int i = 0; i < filas; i++)
        {
            for (int j = 0; j < columnas; j++)
            {
                Texture2D tex; // la textura que se va a dibujar

                // Selecciona la textura según el valor
                switch (cells[i][j].valor)
                {

                case -1000:
                {
                    if (cells[i][j].ocupado == 0)

                    {
                        tex = bomba;
                    }
                    else
                    {
                        tex = bombaexplo;
                    }
                }

                break;

                case -10:
                {
                    if (cells[i][j].ocupado == 0)

                    {
                        tex = bomba;
                    }
                    else
                    {
                        tex = bombaexplo;
                    }
                }

                break;

                case -1:
                {
                    if (cells[i][j].ocupado == 0)

                    {
                        tex = bomba;
                    }
                    else
                    {
                        tex = bombaexplo;
                    }
                }

                break;

                case 1:
                    if (cells[i][j].ocupado == 0)
                    {
                        tex = orvacio1;
                    }
                    else
                    {
                        tex = orlleno1;
                    }
                    break;

                case 10:
                    if (cells[i][j].ocupado == 0)
                    {
                        tex = orvacio2;
                    }
                    else
                    {
                        tex = orlleno2;
                    }
                    break;
                case 100:
                    if (cells[i][j].ocupado == 0)
                    {
                        tex = orvacio3;
                    }
                    else
                    {
                        tex = orlleno3;
                    }

                    break;
                case 1000:
                    if (cells[i][j].ocupado == 0)
                    {
                        tex = orvacio4;
                    }
                    else
                    {
                        tex = orlleno4;
                    }
                    break;

                default:
                    tex = orvacio1;
                    break; // fallback
                }
                DrawHole(tex, cells[i][j].hitbox, 0.85); // ← escala ajustable
            }
        }
        /************************************************************************* */

        /******************************zona reflejada**************** */

        /**for (int i = 0; i < filas; i++)
         {
             for (int j = 0; j < columnas; j++)
             {
                 DrawRectangleLines(
                     cells[i][j].hitbox.x,
                     cells[i][j].hitbox.y,
                     cells[i][j].hitbox.width,
                     cells[i][j].hitbox.height,
                     LIGHTGRAY);
             }
         }*/
        /******************************************************************************* */

        if (estado_j == INCIAJUEGO)
        {
            PauseMusicStream(intro);
            UpdateMusicStream(musica);
            DrawRectangle(0, 0, screenWidth, screenHeight, Fade(BLACK, 0.5f)); 
            DrawText("LISTO?", screenWidth / 2 - 60, screenHeight / 2 - 50, 40, YELLOW);
            DrawText("PRESIONA ESPACIO PARA INICIAR", screenWidth / 2 - 200, screenHeight / 2 + 10, 20, WHITE);

            // Dibuja la pelota en posición inicial "de espera"
            ball.x = caja.x + caja.width / 2;
            ball.y = caja.y + caja.height - 50;
            ball.Draw();

            if (IsKeyPressed(KEY_SPACE))
            {
                estado_j = JUGANDO; // empieza el juego
            }
        }

        /**************************LO QUE HACE LA PELOTA**************************** */

        else
        {
            if (estado_j == JUGANDO || estado_j == PELOTAPARA) 
            {
               ball.Update(dt, caja);
            }

            ball.Draw();

            if (oportunidades <= 0)
            {
                // Solo si no estamos en preguntas y no perdimos aun
                if (estado_j != PREGUNTA && estado_j != PIERDES) {
                    if (puntajefinal >= puntajeobjetivo)
                    {
                        estado_j = PREGUNTA; 
                        calculoRealizado = false;
                    }
                    else
                    {
                        estado_j = PIERDES;
                    }
                }
            }
            else
            {
                if (IsKeyPressed(KEY_SPACE))
                {
                    ball.PARARSE();
                    ball.frenodemano = 0;
                }

                if (ball.separo == 1)
                {
                    bool encontrada = false;

                    for (int i = 0; i < filas && !encontrada; i++)
                    {
                        for (int j = 0; j < columnas && !encontrada; j++)
                        {
                            if (!cells[i][j].ocupado)
                            {
                                if (CheckCollisionCircleRec(Vector2{ball.x, ball.y}, ball.radius, cells[i][j].hitbox))
                                {
                                    cells[i][j].ocupado = 1;
                                    puntajefinal += cells[i][j].valor;
                                    encontrada = true;
                                    oportunidades--;
                                }
                            }
                        }
                    }
                    ball.separo = 0; ball.MUEVETE ();
                }
            }
        }

        DrawText(TextFormat("Pts: %d", puntajefinal), puntaje.x + 30, puntaje.y + 50, 40, GREEN);
        DrawText(TextFormat("Vidas: %d", oportunidades), puntaje.x + 60, puntaje.y + 100, 40, GREEN);
        DrawText(TextFormat("PTS pa GANAR: %d", puntajeobjetivo), puntaje.x + 30, puntaje.y + 600, 20, GREEN);
        DrawText(TextFormat("promedio: %d", promedio), puntaje.x + 30, puntaje.y + 300, 20, GREEN);
        DrawText(TextFormat("VelX: %.2f VelY: %.2f", ball.speedX, ball.speedY), 100, 600, 20, RED);

        if (estado_j == GANAR)
        {
            DrawText("GANASTE", screenWidth/2, screenHeight/2, 50, WHITE);
        }

        if (estado_j == PIERDES)
        {
            DrawText("GAME OVER", screenWidth/2 - 200, screenHeight/2 - 50, 80, WHITE);
            // --- NUEVO: REINICIO CON Q ---
            DrawText("Presiona Q para Reiniciar Nivel", screenWidth/2 - 250, screenHeight/2 + 50, 30, YELLOW);
            
            if(IsKeyPressed(KEY_Q)){
                 // Reiniciar variables
                 puntajefinal = 0; 
                 oportunidades = 5; 
                 intentos = 3;
                 calculoRealizado = false;
                 inputTexto[0] = '\0';
                 contadorTeclas = 0;

                 // --- IMPORTANTE: REGENERAMOS EL MISMO NIVEL ---
                 suma = 0; nopcs = 0;
                 switch (nivel) {
                    case 1: opcs[0]=1; opcs[1]=10; opcs[2]=100; opcs[3]=1000; opcs[4]=100; nopcs=5; break;
                    case 2: opcs[0]=-1; opcs[1]=-10; opcs[2]=-100; opcs[3]=-1000;
                            opcs[4]=1; opcs[5]=10; opcs[6]=100; opcs[7]=1000;
                            opcs[8]=1; opcs[9]=10; opcs[10]=100; opcs[11]=1;
                            opcs[12]=10; opcs[13]=100; opcs[14]=1000; nopcs=15; break;
                    default: opcs[0]=-1; opcs[1]=-10; opcs[2]=-100; opcs[3]=-1000;
                             opcs[4]=1; opcs[5]=10; opcs[6]=100; opcs[8]=1; 
                             opcs[9]=10; opcs[10]=100; opcs[11]=1; opcs[12]=10;
                             opcs[13]=100; opcs[14]=1000; nopcs=15; break;
                 }
                 for (int i = 0; i < nopcs; i++) suma += opcs[i];
                 promedio = (nopcs > 0) ? suma / nopcs : 1;
                 for (int i = 0; i < filas; i++) {
                    for (int j = 0; j < columnas; j++) {
                        cells[i][j].valor = opcs[rand() % nopcs]; 
                        cells[i][j].ocupado = 0;
                    }
                 }
                 int rangomin = promedio * 6.3;
                 puntajeobjetivo = 1 + rand() % rangomin + (rangomin * 1.1);

                 estado_j = INCIAJUEGO; // Vamos de nuevo!
            }
        }

        EndDrawing();
    }

    UnloadMusicStream(intro);
    UnloadMusicStream(musica);

    CloseAudioDevice();
    UnloadTexture(tablero);
    UnloadImage(icon);
    UnloadImage(fondotablero);

    CloseWindow();
}

void DrawHole(Texture2D texture, Rectangle hitbox, float scale)
{
    float destW = (hitbox.width * 0.85) * scale;
    float destH = hitbox.height * scale;
    Rectangle dest = {
        hitbox.x + ((hitbox.width * 0.85f) - destW) / 2.0f,
        hitbox.y + (hitbox.height - destH) / 2,
        destW, destH};
    DrawTexturePro(texture, {0, 0, float(texture.width), float(texture.height)}, dest, {0, 0}, 0.0f, WHITE);
}